Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AraVirtualTour;
using Microsoft.AspNetCore.Authorization;

namespace AraVirtualTour.Controllers
{
    public class StaffController : Controller
    {
        private readonly AppContext _context;

        public StaffController(AppContext context)
        {
            _context = context;
        }

        //GET: VirtualTour/VirtualTour
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Staff()
        {
            return View(await _context.StaffModel.ToListAsync());
        }

        // GET: Staff
        public async Task<IActionResult> Index()
        {
              return _context.StaffModel != null ? 
                          View(await _context.StaffModel.ToListAsync()) :
                          Problem("Entity set 'AppContext.StaffModel'  is null.");
        }

        // GET: Staff/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.StaffModel == null)
            {
                return NotFound();
            }

            var staffModel = await _context.StaffModel
                .FirstOrDefaultAsync(m => m.id == id);
            if (staffModel == null)
            {
                return NotFound();
            }

            return View(staffModel);
        }

        // GET: Staff/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Staff/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Title,Name,Department,Image")] StaffModel staffModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(staffModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(staffModel);
        }

        // GET: Staff/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.StaffModel == null)
            {
                return NotFound();
            }

            var staffModel = await _context.StaffModel.FindAsync(id);
            if (staffModel == null)
            {
                return NotFound();
            }
            return View(staffModel);
        }

        // POST: Staff/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Title,Name,Department,Image")] StaffModel staffModel)
        {
            if (id != staffModel.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(staffModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StaffModelExists(staffModel.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(staffModel);
        }

        // GET: Staff/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.StaffModel == null)
            {
                return NotFound();
            }

            var staffModel = await _context.StaffModel
                .FirstOrDefaultAsync(m => m.id == id);
            if (staffModel == null)
            {
                return NotFound();
            }

            return View(staffModel);
        }

        // POST: Staff/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.StaffModel == null)
            {
                return Problem("Entity set 'AppContext.StaffModel'  is null.");
            }
            var staffModel = await _context.StaffModel.FindAsync(id);
            if (staffModel != null)
            {
                _context.StaffModel.Remove(staffModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StaffModelExists(int id)
        {
          return (_context.StaffModel?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Controllers/ToolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AraVirtualTour;
using System.Diagnostics;
using AraVirtualTour.Models;

namespace AraVirtualTour.Controllers;

public class ToolsController : Controller 
{
    private readonly ILogger<HomeController> _logger;
    private readonly AppContext _context;

    public ToolsController(ILogger<HomeController> logger, AppContext context)
    {
        _logger = logger;
        _context = context;
    }

    public IActionResult Moodle()
    {
        return View();
    }

    public IActionResult Myara()
    {
        return View();
    }

    [HttpGet]
    public IActionResult UsingAraResources()
    {
        return View();
    }
}

Controllers/VirtualTourController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AraVirtualTour;

namespace AraVirtualTour.Controllers
{
    [Authorize(Roles = "admin")]
    public class VirtualTourController : Controller
    {
        private readonly AppContext _context;

        public VirtualTourController(AppContext context)
        {
            _context = context;
        }

        // GET: VirtualTour
        [HttpGet]
        public async Task<IActionResult> Index()
        {
              return _context.VirtualTourModel != null ? 
                          View(await _context.VirtualTourModel.ToListAsync()) :
                          Problem("Entity set 'AppContext.VirtualTourModel'  is null.");
        }

        // GET: VirtualTour/Details/5
        [HttpGet]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.VirtualTourModel == null)
            {
                return NotFound();
            }

            var virtualTourModel = await _context.VirtualTourModel
                .FirstOrDefaultAsync(m => m.id == id);
            if (virtualTourModel == null)
            {
                return NotFound();
            }

            return View(virtualTourModel);
        }

        // GET: VirtualTour/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //GET: VirtualTour/VirtualTour
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> VirtualTour()
        {
            return View(await _context.VirtualTourModel.ToListAsync());
        }

        // POST: VirtualTour/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,Link")] VirtualTourModel virtualTourModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(virtualTourModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(virtualTourModel);
        }

        // GET: VirtualTour/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.VirtualTourModel == null)
            {
                return NotFound();
            }

            var virtualTourModel = await _context.VirtualTourModel.FindAsync(id);
            if (virtualTourModel == null)
            {
                return NotFound();
            }
            return View(virtualTourModel);
        }

        // POST: VirtualTour/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,Link")] VirtualTourModel virtualTourModel)
        {
            if (id != virtualTourModel.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(virtualTourModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VirtualTourModelExists(virtualTourModel.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(virtualTourModel);
        }

        // GET: VirtualTour/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.VirtualTourModel == null)
            {
                return NotFound();
            }

            var virtualTourModel = await _context.VirtualTourModel
                .FirstOrDefaultAsync(m => m.id == id);
            if (virtualTourModel == null)
            {
                return NotFound();
            }

            return View(virtualTourModel);
        }

        // POST: VirtualTour/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.VirtualTourModel == null)
            {
                return Problem("Entity set 'AppContext.VirtualTourModel'  is null.");
            }
            var virtualTourModel = await _context.VirtualTourModel.FindAsync(id);
            if (virtualTourModel != null)
            {
                _context.VirtualTourModel.Remove(virtualTourModel);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VirtualTourModelExists(int id)
        {
          return (_context.VirtualTourModel?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
@using System;
@using Microsoft.AspNetCore.Identity;
@using AraVirtualTour;

@inject SignInManager<AppUserModel> SignInManager
@inject UserManager<AppUserModel> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ara Virtual Tour</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AraVirtualTour.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <img src="~/images/banner.jpg" alt="banner.jpg" width=100% height=50>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/Ara-Landscape-Logo.png" alt="logo.png" height=50></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Staff">Meet the Staff</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VirtualTour" asp-action="VirtualTour">Virtual Tour</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tools" asp-action="UsingAraResources">Using Ara's Tools</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Credit">Credits</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User)) 
                        {
                            <div class="btn-group">
                                <button type="button" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Edit Pages
                                </button>
                                <div class="dropdown-menu">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Index">Edit Staff</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="VirtualTour" asp-action="Index">Edit Virtual Tour</a>
                                </div>
                            </div>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-transparent">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AraVirtualTour - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>